[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[logger]
level = "warning"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[theme]
base = "dark"
